### ISSUE TITLE
gzserver hang during shutdown

### ISSUE THREAD

**Issue by osrf-migration** [osrf/gazebo#2079]
**Original report ([archived issue](https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/issues/2079)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/), GitHub: [scpeters](https://github.com/scpeters)).**

----------------------------------------
Recently, gzserver has been less responsive to `Ctrl+C`. I recently attached to a hanging process (running [test/worlds/revolute_joint_test.world](https://github.com/osrf/gazebo/blob/de341de4c4495efc4b51c3625d11674d6717a5e3/test/worlds/revolute_joint_test.world)) and got a backtrace showing that it is stuck in an infinite loop in `Publisher::Fini`:

~~~
(gdb) bt
#0  __clock_nanosleep (clock_id=0, flags=0, req=0x7ffd5d1a9040, rem=0xffffffffffffffff) at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:49
#1  0x00007f2cbad3c393 in gazebo::common::Time::Sleep (_time=...) at /data_fast/scpeters/ws/gazebo7/src/gazebo/gazebo/common/Time.cc:427
#2  0x00007f2cbad3c557 in gazebo::common::Time::MSleep (_ms=_ms@entry=10) at /data_fast/scpeters/ws/gazebo7/src/gazebo/gazebo/common/Time.cc:446
#3  0x00007f2cb9a222a7 in gazebo::transport::Publisher::Fini (this=0x35cb520) at /data_fast/scpeters/ws/gazebo7/src/gazebo/gazebo/transport/Publisher.cc:266
#4  0x00007f2cb9a199e0 in gazebo::transport::Node::Fini (this=0x35cb370) at /data_fast/scpeters/ws/gazebo7/src/gazebo/gazebo/transport/Node.cc:60
#5  0x00007f2cb960dff7 in gazebo::physics::Entity::Fini (this=this@entry=0x35cafc0) at /data_fast/scpeters/ws/gazebo7/src/gazebo/gazebo/physics/Entity.cc:597
#6  0x00007f2cb95fd073 in gazebo::physics::Collision::Fini (this=0x35cafc0) at /data_fast/scpeters/ws/gazebo7/src/gazebo/gazebo/physics/Collision.cc:99
#7  0x00007f2cb95fb250 in gazebo::physics::Base::RemoveChild (this=this@entry=0x35b76f0, _child=...) at /data_fast/scpeters/ws/gazebo7/src/gazebo/gazebo/physics/Base.cc:248
#8  0x00007f2cb95fb496 in gazebo::physics::Base::Fini (this=this@entry=0x35b76f0) at /data_fast/scpeters/ws/gazebo7/src/gazebo/gazebo/physics/Base.cc:107
#9  0x00007f2cb960e0d0 in gazebo::physics::Entity::Fini (this=this@entry=0x35b76f0) at /data_fast/scpeters/ws/gazebo7/src/gazebo/gazebo/physics/Entity.cc:610
#10 0x00007f2cb963ab63 in gazebo::physics::Link::Fini (this=0x35b76f0) at /data_fast/scpeters/ws/gazebo7/src/gazebo/gazebo/physics/Link.cc:302
#11 0x00007f2cb95fb250 in gazebo::physics::Base::RemoveChild (this=this@entry=0x3014680, _child=...) at /data_fast/scpeters/ws/gazebo7/src/gazebo/gazebo/physics/Base.cc:248
#12 0x00007f2cb95fb6b1 in gazebo::physics::Base::RemoveChild (this=0x3014680, _id=<optimized out>) at /data_fast/scpeters/ws/gazebo7/src/gazebo/gazebo/physics/Base.cc:203
#13 0x00007f2cb95fb450 in gazebo::physics::Base::Fini (this=this@entry=0x35b76f0) at /data_fast/scpeters/ws/gazebo7/src/gazebo/gazebo/physics/Base.cc:100
#14 0x00007f2cb960e0d0 in gazebo::physics::Entity::Fini (this=this@entry=0x35b76f0) at /data_fast/scpeters/ws/gazebo7/src/gazebo/gazebo/physics/Entity.cc:610
#15 0x00007f2cb963ab63 in gazebo::physics::Link::Fini (this=0x35b76f0) at /data_fast/scpeters/ws/gazebo7/src/gazebo/gazebo/physics/Link.cc:302
#16 0x00007f2cb965347e in gazebo::physics::Model::Fini (this=0x3014680) at /data_fast/scpeters/ws/gazebo7/src/gazebo/gazebo/physics/Model.cc:440
#17 0x00007f2cb9690ae6 in gazebo::physics::World::Fini (this=0x154c210) at /data_fast/scpeters/ws/gazebo7/src/gazebo/gazebo/physics/World.cc:857
#18 0x00007f2cb9667a01 in gazebo::physics::remove_worlds () at /data_fast/scpeters/ws/gazebo7/src/gazebo/gazebo/physics/PhysicsIface.cc:155
#19 0x00007f2cb9667a99 in gazebo::physics::fini () at /data_fast/scpeters/ws/gazebo7/src/gazebo/gazebo/physics/PhysicsIface.cc:49
#20 0x00007f2cbafa4507 in gazebo::shutdown () at /data_fast/scpeters/ws/gazebo7/src/gazebo/gazebo/gazebo.cc:140
#21 0x00007f2cbaf910cd in gazebo::Server::Run (this=0xb96130) at /data_fast/scpeters/ws/gazebo7/src/gazebo/gazebo/Server.cc:578
#22 0x0000000000402229 in __cxa_free_exception@plt ()
#23 0x00000000006057b0 in ?? ()
#24 0x00000000004025da in main (argc=3, argv=0x7ffd5d1a9e08) at /var/lib/jenkins/workspace/gazebo7-debbuilder/build/gazebo-7.3.1/gazebo/server_main.cc:25
~~~

Here's the full backtrace; maybe the TopicManager has already died?

~~~
(gdb) thread apply all bt

Thread 19 (Thread 0x7f2c978ad700 (LWP 13263)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007f2cbad1171b in boost::condition_variable::wait (this=0xb29228, m=...) at /usr/include/boost/thread/pthread/condition_variable.hpp:73
#2  0x00007f2cbad0bbdf in gazebo::common::ModelDatabase::UpdateModelCache (this=0x7f2cbb1b8560 <SingletonT<gazebo::common::ModelDatabase>::GetInstance()::t>, _fetchImmediately=false) at /data_fast/scpeters/ws/gazebo7/src/gazebo/gazebo/common/ModelDatabase.cc:284
#3  0x00007f2cb7647a4a in ?? () from /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.54.0
#4  0x00007f2cb8922184 in start_thread (arg=0x7f2c978ad700) at pthread_create.c:312
#5  0x00007f2cb9d4537d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 18 (Thread 0x7f2c96de3700 (LWP 13264)):
#0  0x00007f2cb9d45a13 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007f2cb9a04dc8 in boost::asio::detail::epoll_reactor::run (this=0xbba540, block=<optimized out>, ops=...) at /usr/include/boost/asio/detail/impl/epoll_reactor.ipp:392
#2  0x00007f2cb9a0a558 in do_run_one (ec=..., this_thread=..., lock=..., this=<optimized out>) at /usr/include/boost/asio/detail/impl/task_io_service.ipp:368
#3  boost::asio::detail::task_io_service::run (this=0xbba0b0, ec=...) at /usr/include/boost/asio/detail/impl/task_io_service.ipp:153
#4  0x00007f2cb9a192c6 in boost::asio::io_service::run (this=0xbb9700) at /usr/include/boost/asio/impl/io_service.ipp:59
#5  0x00007f2cb7647a4a in ?? () from /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.54.0
#6  0x00007f2cb8922184 in start_thread (arg=0x7f2c96de3700) at pthread_create.c:312
#7  0x00007f2cb9d4537d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 17 (Thread 0x7f2c965e2700 (LWP 13265)):
#0  __clock_nanosleep (clock_id=0, flags=0, req=0x7f2c965e1d10, rem=0xffffffffffffffff) at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:49
#1  0x00007f2cbad3c393 in gazebo::common::Time::Sleep (_time=...) at /data_fast/scpeters/ws/gazebo7/src/gazebo/gazebo/common/Time.cc:427
#2  0x00007f2cbad3c557 in gazebo::common::Time::MSleep (_ms=_ms@entry=10) at /data_fast/scpeters/ws/gazebo7/src/gazebo/gazebo/common/Time.cc:446
#3  0x00007f2cbafa02f5 in gazebo::Master::Run (this=0xbb91b0) at /data_fast/scpeters/ws/gazebo7/src/gazebo/gazebo/Master.cc:382
#4  0x00007f2cba5dda60 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007f2cb8922184 in start_thread (arg=0x7f2c965e2700) at pthread_create.c:312
#6  0x00007f2cb9d4537d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 16 (Thread 0x7f2c8f05f700 (LWP 13268)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007f2cb114c690 in ?? () from /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.8.1
#2  0x00007f2cb114b6af in Ogre::DefaultWorkQueue::waitForNextRequest() () from /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.8.1
#3  0x00007f2cb114bb24 in Ogre::DefaultWorkQueue::_threadMain() () from /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.8.1
#4  0x00007f2cb7647a4a in ?? () from /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.54.0
#5  0x00007f2cb8922184 in start_thread (arg=0x7f2c8f05f700) at pthread_create.c:312
#6  0x00007f2cb9d4537d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 15 (Thread 0x7f2c8e85e700 (LWP 13269)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007f2cb114c690 in ?? () from /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.8.1
#2  0x00007f2cb114b6af in Ogre::DefaultWorkQueue::waitForNextRequest() () from /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.8.1
#3  0x00007f2cb114bb24 in Ogre::DefaultWorkQueue::_threadMain() () from /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.8.1
#4  0x00007f2cb7647a4a in ?? () from /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.54.0
#5  0x00007f2cb8922184 in start_thread (arg=0x7f2c8e85e700) at pthread_create.c:312
#6  0x00007f2cb9d4537d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 14 (Thread 0x7f2c8e05d700 (LWP 13270)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007f2cb114c690 in ?? () from /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.8.1
#2  0x00007f2cb114b6af in Ogre::DefaultWorkQueue::waitForNextRequest() () from /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.8.1
#3  0x00007f2cb114bb24 in Ogre::DefaultWorkQueue::_threadMain() () from /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.8.1
#4  0x00007f2cb7647a4a in ?? () from /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.54.0
#5  0x00007f2cb8922184 in start_thread (arg=0x7f2c8e05d700) at pthread_create.c:312
#6  0x00007f2cb9d4537d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 13 (Thread 0x7f2c8d85c700 (LWP 13271)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007f2cb114c690 in ?? () from /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.8.1
#2  0x00007f2cb114b6af in Ogre::DefaultWorkQueue::waitForNextRequest() () from /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.8.1
#3  0x00007f2cb114bb24 in Ogre::DefaultWorkQueue::_threadMain() () from /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.8.1
#4  0x00007f2cb7647a4a in ?? () from /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.54.0
#5  0x00007f2cb8922184 in start_thread (arg=0x7f2c8d85c700) at pthread_create.c:312
#6  0x00007f2cb9d4537d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 12 (Thread 0x7f2c8d05b700 (LWP 13272)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007f2cb114c690 in ?? () from /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.8.1
#2  0x00007f2cb114b6af in Ogre::DefaultWorkQueue::waitForNextRequest() () from /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.8.1
#3  0x00007f2cb114bb24 in Ogre::DefaultWorkQueue::_threadMain() () from /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.8.1
#4  0x00007f2cb7647a4a in ?? () from /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.54.0
#5  0x00007f2cb8922184 in start_thread (arg=0x7f2c8d05b700) at pthread_create.c:312
#6  0x00007f2cb9d4537d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 11 (Thread 0x7f2c8c85a700 (LWP 13273)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007f2cb114c690 in ?? () from /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.8.1
#2  0x00007f2cb114b6af in Ogre::DefaultWorkQueue::waitForNextRequest() () from /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.8.1
#3  0x00007f2cb114bb24 in Ogre::DefaultWorkQueue::_threadMain() () from /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.8.1
#4  0x00007f2cb7647a4a in ?? () from /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.54.0
#5  0x00007f2cb8922184 in start_thread (arg=0x7f2c8c85a700) at pthread_create.c:312
#6  0x00007f2cb9d4537d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 10 (Thread 0x7f2c77fff700 (LWP 13274)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007f2cb114c690 in ?? () from /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.8.1
#2  0x00007f2cb114b6af in Ogre::DefaultWorkQueue::waitForNextRequest() () from /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.8.1
#3  0x00007f2cb114bb24 in Ogre::DefaultWorkQueue::_threadMain() () from /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.8.1
#4  0x00007f2cb7647a4a in ?? () from /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.54.0
#5  0x00007f2cb8922184 in start_thread (arg=0x7f2c77fff700) at pthread_create.c:312
#6  0x00007f2cb9d4537d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 9 (Thread 0x7f2c777fe700 (LWP 13275)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007f2cb114c690 in ?? () from /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.8.1
#2  0x00007f2cb114b6af in Ogre::DefaultWorkQueue::waitForNextRequest() () from /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.8.1
#3  0x00007f2cb114bb24 in Ogre::DefaultWorkQueue::_threadMain() () from /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.8.1
#4  0x00007f2cb7647a4a in ?? () from /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.54.0
#5  0x00007f2cb8922184 in start_thread (arg=0x7f2c777fe700) at pthread_create.c:312
#6  0x00007f2cb9d4537d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 8 (Thread 0x7f2c74600700 (LWP 13279)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007f2cb84fa2db in ?? () from /usr/lib/libtbb.so.2
#2  0x00007f2cb84fa2f9 in ?? () from /usr/lib/libtbb.so.2
#3  0x00007f2cb8922184 in start_thread (arg=0x7f2c74600700) at pthread_create.c:312
#4  0x00007f2cb9d4537d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 7 (Thread 0x7f2c6bfff700 (LWP 13280)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007f2cb84fa2db in ?? () from /usr/lib/libtbb.so.2
#2  0x00007f2cb84fa2f9 in ?? () from /usr/lib/libtbb.so.2
#3  0x00007f2cb8922184 in start_thread (arg=0x7f2c6bfff700) at pthread_create.c:312
#4  0x00007f2cb9d4537d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 6 (Thread 0x7f2c6bbfe700 (LWP 13281)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007f2cb84fa2db in ?? () from /usr/lib/libtbb.so.2
#2  0x00007f2cb84fa2f9 in ?? () from /usr/lib/libtbb.so.2
#3  0x00007f2cb8922184 in start_thread (arg=0x7f2c6bbfe700) at pthread_create.c:312
#4  0x00007f2cb9d4537d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 5 (Thread 0x7f2c6b7fd700 (LWP 13282)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007f2cb84fa2db in ?? () from /usr/lib/libtbb.so.2
#2  0x00007f2cb84fa2f9 in ?? () from /usr/lib/libtbb.so.2
#3  0x00007f2cb8922184 in start_thread (arg=0x7f2c6b7fd700) at pthread_create.c:312
#4  0x00007f2cb9d4537d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 4 (Thread 0x7f2c6b3fc700 (LWP 13284)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007f2cb84fa2db in ?? () from /usr/lib/libtbb.so.2
#2  0x00007f2cb84fa2f9 in ?? () from /usr/lib/libtbb.so.2
#3  0x00007f2cb8922184 in start_thread (arg=0x7f2c6b3fc700) at pthread_create.c:312
#4  0x00007f2cb9d4537d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 3 (Thread 0x7f2c6affb700 (LWP 13283)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007f2cb84fa2db in ?? () from /usr/lib/libtbb.so.2
#2  0x00007f2cb84fa2f9 in ?? () from /usr/lib/libtbb.so.2
#3  0x00007f2cb8922184 in start_thread (arg=0x7f2c6affb700) at pthread_create.c:312
#4  0x00007f2cb9d4537d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 2 (Thread 0x7f2c6abfa700 (LWP 13285)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007f2cb84fa2db in ?? () from /usr/lib/libtbb.so.2
#2  0x00007f2cb84fa2f9 in ?? () from /usr/lib/libtbb.so.2
#3  0x00007f2cb8922184 in start_thread (arg=0x7f2c6abfa700) at pthread_create.c:312
#4  0x00007f2cb9d4537d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 1 (Thread 0x7f2cbb350880 (LWP 13262)):
#0  __clock_nanosleep (clock_id=0, flags=0, req=0x7ffd5d1a9040, rem=0xffffffffffffffff) at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:49
#1  0x00007f2cbad3c393 in gazebo::common::Time::Sleep (_time=...) at /data_fast/scpeters/ws/gazebo7/src/gazebo/gazebo/common/Time.cc:427
#2  0x00007f2cbad3c557 in gazebo::common::Time::MSleep (_ms=_ms@entry=10) at /data_fast/scpeters/ws/gazebo7/src/gazebo/gazebo/common/Time.cc:446
#3  0x00007f2cb9a222a7 in gazebo::transport::Publisher::Fini (this=0x35cb520) at /data_fast/scpeters/ws/gazebo7/src/gazebo/gazebo/transport/Publisher.cc:266
#4  0x00007f2cb9a199e0 in gazebo::transport::Node::Fini (this=0x35cb370) at /data_fast/scpeters/ws/gazebo7/src/gazebo/gazebo/transport/Node.cc:60
#5  0x00007f2cb960dff7 in gazebo::physics::Entity::Fini (this=this@entry=0x35cafc0) at /data_fast/scpeters/ws/gazebo7/src/gazebo/gazebo/physics/Entity.cc:597
#6  0x00007f2cb95fd073 in gazebo::physics::Collision::Fini (this=0x35cafc0) at /data_fast/scpeters/ws/gazebo7/src/gazebo/gazebo/physics/Collision.cc:99
#7  0x00007f2cb95fb250 in gazebo::physics::Base::RemoveChild (this=this@entry=0x35b76f0, _child=...) at /data_fast/scpeters/ws/gazebo7/src/gazebo/gazebo/physics/Base.cc:248
#8  0x00007f2cb95fb496 in gazebo::physics::Base::Fini (this=this@entry=0x35b76f0) at /data_fast/scpeters/ws/gazebo7/src/gazebo/gazebo/physics/Base.cc:107
#9  0x00007f2cb960e0d0 in gazebo::physics::Entity::Fini (this=this@entry=0x35b76f0) at /data_fast/scpeters/ws/gazebo7/src/gazebo/gazebo/physics/Entity.cc:610
#10 0x00007f2cb963ab63 in gazebo::physics::Link::Fini (this=0x35b76f0) at /data_fast/scpeters/ws/gazebo7/src/gazebo/gazebo/physics/Link.cc:302
#11 0x00007f2cb95fb250 in gazebo::physics::Base::RemoveChild (this=this@entry=0x3014680, _child=...) at /data_fast/scpeters/ws/gazebo7/src/gazebo/gazebo/physics/Base.cc:248
#12 0x00007f2cb95fb6b1 in gazebo::physics::Base::RemoveChild (this=0x3014680, _id=<optimized out>) at /data_fast/scpeters/ws/gazebo7/src/gazebo/gazebo/physics/Base.cc:203
#13 0x00007f2cb95fb450 in gazebo::physics::Base::Fini (this=this@entry=0x35b76f0) at /data_fast/scpeters/ws/gazebo7/src/gazebo/gazebo/physics/Base.cc:100
#14 0x00007f2cb960e0d0 in gazebo::physics::Entity::Fini (this=this@entry=0x35b76f0) at /data_fast/scpeters/ws/gazebo7/src/gazebo/gazebo/physics/Entity.cc:610
#15 0x00007f2cb963ab63 in gazebo::physics::Link::Fini (this=0x35b76f0) at /data_fast/scpeters/ws/gazebo7/src/gazebo/gazebo/physics/Link.cc:302
#16 0x00007f2cb965347e in gazebo::physics::Model::Fini (this=0x3014680) at /data_fast/scpeters/ws/gazebo7/src/gazebo/gazebo/physics/Model.cc:440
#17 0x00007f2cb9690ae6 in gazebo::physics::World::Fini (this=0x154c210) at /data_fast/scpeters/ws/gazebo7/src/gazebo/gazebo/physics/World.cc:857
#18 0x00007f2cb9667a01 in gazebo::physics::remove_worlds () at /data_fast/scpeters/ws/gazebo7/src/gazebo/gazebo/physics/PhysicsIface.cc:155
#19 0x00007f2cb9667a99 in gazebo::physics::fini () at /data_fast/scpeters/ws/gazebo7/src/gazebo/gazebo/physics/PhysicsIface.cc:49
#20 0x00007f2cbafa4507 in gazebo::shutdown () at /data_fast/scpeters/ws/gazebo7/src/gazebo/gazebo/gazebo.cc:140
#21 0x00007f2cbaf910cd in gazebo::Server::Run (this=0xb96130) at /data_fast/scpeters/ws/gazebo7/src/gazebo/gazebo/Server.cc:578
#22 0x0000000000402229 in __cxa_free_exception@plt ()
#23 0x00000000006057b0 in ?? ()
#24 0x00000000004025da in main (argc=3, argv=0x7ffd5d1a9e08) at /var/lib/jenkins/workspace/gazebo7-debbuilder/build/gazebo-7.3.1/gazebo/server_main.cc:25
(gdb) 
~~~

**Comment by catskul** [comment]
Still appears to be a problem.
