### ISSUE TITLE
gzclient crash when inserting Cessna model

### ISSUE THREAD

**Issue by osrf-migration** [osrf/gazebo#2384]
**Original report ([archived issue](https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/issues/2384)) by Louise Poubel (Bitbucket: [chapulina](https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/), GitHub: [chapulina](https://github.com/chapulina)).**

----------------------------------------
Backtrace:

~~~
terminate called after throwing an instance of 'gazebo::common::Exception'
[New Thread 0x7fff461f8700 (LWP 21742)]

Thread 1 "gzclient" received signal SIGABRT, Aborted.
0x00007ffff3368428 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff3368428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff336a02a in __GI_abort () at abort.c:89
#2  0x00007ffff39a284d in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff39a06b6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff39a0701 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff39a0919 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff4e40ac3 in gazebo::common::SubMesh::Vertex (this=0x6bfacb0, _i=32)
    at /media/louise/TERA/code/gazeboA/gazebo/common/Mesh.cc:560
#7  0x00007ffff24788d0 in gazebo::rendering::RayQuery::SelectMeshTriangle (this=0x7fffffffc780, _x=973, _y=376, _visual=
    std::shared_ptr (count 4, weak 2) 0x5db7640, _intersect=..., _triangle=...)
    at /media/louise/TERA/code/gazeboA/gazebo/rendering/RayQuery.cc:94
#8  0x00007ffff24e8b5f in gazebo::rendering::Scene::FirstContact (this=0x1b7c7c0, _camera=..., _mousePos=..., _position=...)
    at /media/louise/TERA/code/gazeboA/gazebo/rendering/Scene.cc:1159
#9  0x00007ffff24501e4 in gazebo::rendering::OrbitViewController::HandleMouseEvent (this=0x3825aa0, _event=...)
    at /media/louise/TERA/code/gazeboA/gazebo/rendering/OrbitViewController.cc:171
~~~

Not sure if it is related, but `RayQuery::SelectMeshTriangle` was changed on [pull request #2688](https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/pull-requests/2688)

**Comment by HighPriest** [comment]
Shouldn't this issue be closed?

**Comment by chapulina** [comment]
Yup, it looks like it's been fixed, thanks for the pointer!
